### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by SimonHegele** [biointec/jabba#17]
Hello, 
I tried installing Jabba, but cloning it failed. It seems that the link to the brownie repo is inactive.
After downloading everything manually, i then tried to install Jabba following the description but it failed. I attached a log.
[log.txt](https://github.com/user-attachments/files/18086333/log.txt)

**Comment by gmiclotte** [comment]
Dear Simon

Both the brownie and the compilation issues should now be resolved. If you still have compilation issues please specify which compiler you are using and I can have another look.

Kind regards
Giles Miclotte

**Comment by SimonHegele** [comment]
Thank you very much for the fast response!
Cloning this repository is now working completely fine, but I am still not able to install Jabba.

The commands for the installation differ between the readme.md-file, the wiki and the compile.sh-file.
For convenience I used the compile.sh-file. I have saved both the stdout and stderr and attached them.

My gcc-, make-, cmake-versions are:
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
GNU Make 4.3
cmake version 3.28.3

Make failed for brownie:
```/usr/bin/ld: CMakeFiles/brownie.dir/suffix_tree.c.o:(.bss+0x18): multiple definition of `ST_ERROR'; CMakeFiles/brownie.dir/solutioncomp.cpp.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/brownie.dir/build.make:407: src/brownie] Error 1
make[1]: *** [CMakeFiles/Makefile2:174: src/CMakeFiles/brownie.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:139: all] Error 2
cp: cannot stat './brownie/build/src/brownie': No such file or directory```

[stderr.txt](https://github.com/user-attachments/files/18094721/stderr.txt)
[stdout.txt](https://github.com/user-attachments/files/18094722/stdout.txt)

**Comment by gmiclotte** [comment]
Dear Simon


The compilation commands should be about the same, the differences being the creation of the bin folder (absent in readme), and the compilation of brownie and karect (only present in compile.sh script). Either way, you cannot really go wrong as far as I am aware.

Regarding your compilation issue, it looks like the brownie submodule was outdated. The error you mention here was fixed in the latest brownie version. This submodule should now be updated.

I'll have a look at the other issue on the brownie repo now.


Kind regards
Giles Miclotte

**Comment by SimonHegele** [comment]
Dear Giles,

still couldn't install it on my machine, but I think that is something on my part: apparently I am missing an important library 

```
/usr/bin/ld: cannot find /lib64/libpthread.so.0: No such file or directory
/usr/bin/ld: cannot find /usr/lib64/libpthread_nonshared.a: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/jabba.dir/build.make:341: src/jabba] Error 1
make[2]: Leaving directory '/root/jabba/build'
make[1]: *** [CMakeFiles/Makefile2:118: src/CMakeFiles/jabba.dir/all] Error 2
make[1]: Leaving directory '/root/jabba/build'
make: *** [Makefile:94: all] Error 2
```

I will figure out where to get it from, but on our servers it is apparently available so I was able to install Jabba there.

I did two more things different / in addition to what is in the wiki:
1. Instead of `cp -b build/src/Jabba bin/Jabba` I used `cp -b build/src/Jabba bin/jabba` (lower-case vs upper case)
2. `export PATH=<jabba_path>/bin:$PATH`

From there Jabba ran successfully, so thank you very very much for your support!

There is however one thing that is odd about the results.

AlignQC reported that 99.7% of my raw reads could be aligned to the reference genome.
Any other tool that I have tried was able to maintain or improve that rate.
However, after correction with Jabba this rate dropped to 84.4%. The reads that still could be aligned are very good with an error rate of 2.35% reported by NanoSim and 99.9% of there bases being aligned according to AlignQC but I wonder what happend to the rest of the reads. Do you have any idea? Also some reads (~0.3%) were lost entirely.

My brownie command: 
`brownie graphCorrection -p brownie_graph -t 7 illumina.fastq`

My jabba command:
`jabba --dbgk 31 --graph brownie_graph/DBGraph.fasta -fasta ont.fasta`

Best,
Simon

**Comment by gmiclotte** [comment]
Dear Simon


I'm glad to hear you were able to successfully compile the software on your server!

Regarding the issue with the corrected reads, it seems likely that Jabba was overly aggressive in correcting them, by following a path in the de Bruijn graph. This might have caused some reads to be excessively altered and rendered unalignable. I haven’t worked with read error correction in quite some time, so unfortunately I don’t recall the specific quirks and details.


Kind regards
Giles Miclotte
